### ISSUE TITLE
Support doing checkpoint sync from file

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/lambda_ethereum_consensus#726] opened 2024-02-07 14:05 UTC
We currently support fetching a weak subjectivity checkpoint (finalized beacon state and block) from a URL. We'd like to also be able to fetch it from a file/files.

**Comment by Arkenan** [comment] 2024-07-03 11:40
Duplicate of completed: #806

**Closed by Arkenan** 2024-07-03 11:40 UTC
Labels: good first issue
