### ISSUE TITLE
WSL2 support

### ISSUE THREAD

**Issue by ayushm2003** [lambdaclass/lambda_ethereum_consensus#183] opened 2023-09-08 21:45 UTC
`make iex` fails when trying to build on wsl2

Tried both approaches, with and without asdf.

#### With asdf -

![image](https://github.com/lambdaclass/lambda_ethereum_consensus/assets/62571011/e652cfe7-5248-4ed4-9834-6c6ce272c24d)

#### Without asdf -

![image](https://github.com/lambdaclass/lambda_ethereum_consensus/assets/62571011/3290792a-0642-4085-958c-5c80a7ea8c34)

### Comment from tg -

The flags to compile the libp2p NIF into a shared library are a bit specific, and might not work on all environments. Those are in the [Makefile, line 26](https://github.com/lambdaclass/lambda_ethereum_consensus/blob/main/Makefile#L26): `CFLAGS += -Wl,-undefined -Wl,dynamic_lookup -fPIC -shared`

**Comment by MegaRedHand** [comment] 2023-09-09 04:39
I tried running it with wsl2/ubuntu and it works. Could you share the output of `which gcc` and `gcc --version` ?

**Comment by ayushm2003** [comment] 2023-09-09 17:16
![image](https://github.com/lambdaclass/lambda_ethereum_consensus/assets/62571011/cf9e03a0-472b-4fac-abe5-f458ccdb250c)

**Comment by MegaRedHand** [comment] 2023-09-09 19:59
It seems to be with Ubuntu 20.04 in particular (maybe just gcc-9). With Ubuntu 22.04 (gcc-11) it seems to work just fine.

**Comment by ayushm2003** [comment] 2023-09-10 20:38
Updated my distro, to 22.04 and started fresh, but the error still persists.
The error seems to be with something go version related? although `which go` is `/home/ayush/.asdf/shims/go`

**Comment by MegaRedHand** [comment] 2023-09-10 20:45
What's the error message? Still the same go1.20.8 message from the issue description?

**Comment by ayushm2003** [comment] 2023-09-10 21:17
yes

**Comment by MegaRedHand** [comment] 2023-09-11 12:37
Maybe your [GOROOT env var isn't properly configured](https://stackoverflow.com/questions/46693653/compile-version-go1-9-does-not-match-go-tool-version-go1-9-1)?

**Comment by ayushm2003** [comment] 2023-09-11 22:32
thanks! the error got resolved by removing my previously installed go and fixing the `GOROOT` var

getting this though once the terminal starts, is this normal?

![image](https://github.com/lambdaclass/lambda_ethereum_consensus/assets/62571011/e2ae64f6-b98f-44d9-be0e-2df654e7dc54)

the tests pass though
`1 doctest, 1 property, 19 tests, 0 failures, 3 skipped`

**Comment by MegaRedHand** [comment] 2023-09-12 00:30
👏 . Yeah, those logs are normal and we already have PRs addressing them. The first one is safe to ignore, as it's due to us not having a way to correctly decode the message, and using a random type (fixed in #196), and I think the second one is caused by peers disconnecting from our node without properly sending the goodbye payload through the stream (we should definitely check it, but for now it's not a priority, and it's marked as _debug_ down from _error_ in #188).

**Comment by MegaRedHand** [comment] 2023-09-12 00:35
**Conclusion:**

The first error didn't happen because of WSL specifically, but due to the underlying Ubuntu 20.04 image. Upgrading the version to 22.04 fixed the issue.

The second error was due to a misconfigured Go environment, and was fixed by removing the previous installation, reinstalling with _asdf_, and fixing the `GOPATH` variable (as detailed in https://stackoverflow.com/questions/46693653/compile-version-go1-9-does-not-match-go-tool-version-go1-9-1)

**Closed by MegaRedHand** 2023-09-12 00:35 UTC
